version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: cmsuser
      POSTGRES_PASSWORD: cms@123
      POSTGRES_DB: cms
    restart: always
    volumes:
      - shared_data:/var/lib/postgresql/data  

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - postgres
    command: >
      sh -c "npm run migration:run && npm start"
    restart: always
volumes:
  shared_data:    
